- src/config_example.h
- src/homeplate.h
- src/mqtt.cpp
Quick hack for the homeplate to show up in HA Device Registry via MQTT Discovery
> add device info to show homeplate in device registry

- src/homeplate.h
- src/mqtt.cpp
- src/sleep.cpp
Useful for having a certain activity displayed for a shorter time range or having more frequent updates.
By using the activity/run topic, it only overwrites the sleep duration once, so no need to keep track of setting
the interval up and down manually.
Usage example:
I have an automation for commute times that runs every 5 minutes in the morning between 6 and 9.
After the sensor update I send mqtt.publish({"action": "hass", "refresh": "300"}) to have a shorter update interval
for the next run so the information on the display is more up-to-date.
> add parameter refresh to mqtt activity for dynamic sleep time override

- hass.md
- src/mqtt.cpp
This patch makes use of the MQTT_NODE_ID and MQTT_DEVICE_NAME values to form unique mqtt topics so there can be multiple devices at the same time.
> Use node_id in unique_id and mqtt topics

- src/mqtt.cpp
reintroduce identifier reverted in 56071c8. needed to increment buffer size to hold full serialized mqtt string
> add macaddr to device identifiers

- src/input.cpp
- src/main.cpp
- src/sleep.cpp
- vcom_src/vcom.cpp
MCP23017_INTFA is the register address, not the i2c bus addr. Using the newly introduced IO_INT_ADDR resolved also the touchpad sensivity problem mentioned in 6e512f72824ace4b47cf3539a510ad54e1c30a68. In main.c I made use of the library exposed function that leaves out dealing with the expander addresses completely.
(I am right now testing how this can also be incorporated in the checkBootPads - I will get a inkplate10v2 soon and that has a different expander chip)
> Fix expander i2c address and touchpad issues

- src/homeplate.h
The inkplate library v6.0.0 has updated the battery voltage readout, now giving correct readouts using the calibrated adc. This patch reflects the recommended voltages for a 3.7V battery.
> update battery voltages to match readout of inkplate library

- src/homeplate.h
After some more longterm tests, this gives a better battery wearlevel and a saver deep discharge prevention.
> raise battery low voltage a little to get better battery wearlevel

- src/util.cpp
When readout voltage is below BATTERY_VOLTAGE_LOW (for example 3.37V < 3.4V), then an integer overflow
occurs in the calculation of uint percentage, leading to return 100%.
> skip battery percentage calculation to avoid integer overflow

- src/sleep.cpp
See esp_sleep_enable_timer_wakeup(uint64_t time_in_us)
With uint32_t a maximum sleep time of ~4294s/71min is possible, before the counter wraps around.
Fixes #34
> add datatype to factor to get uint64_t

- src/mqtt.cpp
- src/qr.cpp
- src/time.cpp
Fix to exclude certain modules (NTP, QR, MQTT) from running when variables are not defined in config.h
Fixes #33
> Fix enable defines (NTP, QR, MQTT)

- src/mqtt.cpp
* ex. "HomePlate WiFi Signal" -> "WiFi Signal"
* according to HA PSA MQTT Name changes in 2023.08
See: https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099/8
Fixes #32
> remove device name from mqtt entity name

- README.md
Replace the link to Kiosk-Mode plugin to a repository which is maintained. Currently linked repo is archived and not up to date.
> Update README.md to link to an active Kios-mode Repo

- src/network.cpp
See https://github.com/espressif/arduino-esp32/issues/6278, setHostname needs to be called before setting the wifi  mode cause otherwise it will not / not always be set correctly
> fix: set hostname before mode

- src/config_example.h
- src/homeplate.h
The default timeout of 5 minutes for the qr code / info seemed a bit long to me, took some time to figure out where that 5 min timeout came from. This pr makes that setting clearly user configurable
> feat: make TIME_TO_QUICK_SLEEP_SEC user configurable

- platformio.ini
Both the Inkplate library as ESP32Time have some fixes. Not sure if homeplate is hitting any of those bugs, but upgrading doesn't seem to cause issues after testing.
> chore: upgrade dependencies

- .github/workflows/build.yml
- .gitignore
- README.md
- lib/libhomeplate/src/sleep_duration.cpp
- lib/libhomeplate/src/sleep_duration.h
- platformio.ini
- src/activity.cpp
- src/config_example.cpp
- src/config_example.h
- src/homeplate.h
- src/mqtt.cpp
- src/time.cpp
- test/test_get_sleep_duration.cpp
This PR adds support to configure different sleep durations per day-of-week, hour and minute. It should basically support the most common configs as is described in [hass.md](../blob/main/hass.md), so instead of using home-assistant to keep changing the sleep duration it's just baked into the homeplate fw :)
- see `config_example.cpp` for example config
- I had to change the env's a little bit to be able to run the unit tests
> feat: add support for variable sleep durations

- src/config_example.h
As discussed [here](https://github.com/lanrat/homeplate/pull/45#issuecomment-2295172008), there's a wrong line in the example config that may confuse lib users.
This PR will revert the wrongful rename, thus making the project run when copying from the example config.
> fix: revert rename of sleep_duration.h in example config

- README.md
- hass.md
- src/activity.cpp
- src/config_example.cpp
- src/config_example.h
- src/homeplate.h
- src/mqtt.cpp
Ok, third time is the charm 😞 
This is starting to get embarrassing, but in my defense I didn't realize before I had configured my `TIME_TO_SLEEP_MIN` to 5 minutes and also configured the variable sleep duration's during the day to be 5 minutes. So while I was working on this during the day, it seemed it was using the correct sleep duration even though it was just using the default sleep :(
As a similar issue could exists for other people when your configured time slots are f.e. not continuous, I realized it would be helpful to store the actual sleep duration as diagnostic in mqtt/hass so you can check it's correct even when you are normally sleeping.
I'll make this a draft pr for now and check tomorrow that it's actually fixed now...
fyi @felixh10r
> fix: sleep duration again & send sleep duration to mqtt

- src/mqtt.cpp
Because `mqttRun` was true by default, it immediately sent a mqtt update when connecting to mqtt. But then after executing the activity (which homeplate always does after booting/waking up), it also sent a mqtt status which meant that mqtt data got updated twice every time the homeplate wakes up.
Not having to sent the mqtt data twice during a single wake up could improve battery life
> fix: dont send mqtt status twice during single activity

- src/mqtt.cpp
leads to endless sleep otherwise in [sleep.cpp#L86](https://github.com/lanrat/homeplate/blob/127031889d91811e4f3c0c8aae7ab8567cbac561/src/sleep.cpp#L86)
> fix mqtt logic if no MQTT_HOST is defined

- src/info.cpp
When using the info display, it mostly shows an error for MQTT and WiFi due to the task running earlier/faster than the others. Around 500ms of delay seem to be sufficient to have the correct values there.
> update infodisplay when WiFi and MQTT become available
